vich_uploader:
    db_driver: orm

    mappings:
        dataset_files:
            uri_prefix: /uploads/datasets
            upload_destination: '%kernel.project_dir%/public/uploads/datasets'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true